trigger:
  name: gitlab-trigger
  identifier: gitlabtrigger
  enabled: true
  description: ""
  tags: {}
  orgIdentifier: Ansibler
  stagesToExecute: []
  projectIdentifier: ssh
  pipelineIdentifier: hmcvhgm
  source:
    type: Webhook
    spec:
      type: Gitlab
      spec:
        type: Push
        spec:
          connectorRef: gitlab
          autoAbortPreviousExecutions: false
          payloadConditions:
            - key: targetBranch
              operator: Equals
              value: main
          headerConditions: []
          actions: []
